#define HOME_PAGE "./html_files/1_intro.html"
#define MAIN_PAGE "./html_files/2_start.html"
#define GAME_PLAYING_PAGE "./html_files/3_first_turn.html"
#define KEYWORD_ACCEPTED_PAGE "./html_files/4_accepted.html"
#define KEYWORD_DISCARDED_PAGE "./html_files/5_discarded.html"
#define GAME_COMPLETED_PAGE "./html_files/6_endgame.html"
#define GAME_OVER_PAGE "./html_files/7_gameover.html"
#define FAV_ICON "./html_files/fav_icon.png"
